### ISSUE TITLE
Add swipe gestures for smartphones

### ISSUE THREAD

**Issue by olastor** [Sirimangalo/meditation-plus-angular#100]
For opening the `sidenav` (for example)

**Comment by binarious** [comment]
People seem to use Hammer.js for this: https://stackoverflow.com/questions/35728451/using-mobile-events-in-angular2

**Comment by olastor** [comment]
In angular2 there already exists _hammer_gestures_ (in`node_modules/@angular/platform-browser/src/dom/events`), but it's marked as experimental. Installing Hammer.js manually via `npm` creates conflicts (with the typings I think).

**Comment by binarious** [comment]
A lot of things in Angular are marked as experimental. That's ok 😄 . Material2 also uses Hammer.js: https://github.com/angular/material2/pull/294

**Comment by binarious** [comment]
Blocked by https://github.com/Sirimangalo/meditation-plus-angular/issues/166 since the functionality is in Material2 alpha 7.

**Comment by binarious** [comment]
Alpha 7 is now integrated. This is not blocked anymore.

**Comment by binarious** [comment]
Done via https://github.com/Sirimangalo/meditation-plus-angular/pull/235.
