### ISSUE TITLE
Longer 'Finished meditating' list

### ISSUE THREAD

**Issue by quizasperfidia** [Sirimangalo/meditation-plus-angular#103]
I've noticed the list of people that have finished meditating is usually very small. I'm assuming this is because they disappear after a certain amount of time? On the old site the list is really long and I find it motivating to see everyone that's finished meditating.  Is there anyway to make the list longer so we can see more previous mediators?

**Comment by binarious** [comment]
It's limited to the meditations of the last hour. We can change it to the last three hours, which was the timespan of the old site.

**Comment by binarious** [comment]
Increased to three hours in https://github.com/Sirimangalo/meditation-plus-server/commit/2eee9ec2633c5da277435ca92d86a6d06a0c1db6.
