### ISSUE TITLE
distinguish users who meditated (green) vs. non-meditators (orange)

### ISSUE THREAD

**Issue by olastor** [Sirimangalo/meditation-plus-angular#107]
Feature from the 'old' site
Edit: Necessary for questions and user list

**Comment by binarious** [comment]
Can you describe what it means?

Feature from the 'old' site

**Comment by olastor** [comment]
At http://meditation.sirimangalo.org/ the questions are marked yellow, if the person is not in the recently meditated list and green if so.

**Comment by binarious** [comment]
@yuttadhammo Still required?

**Comment by yuttadhammo** [comment]
It is useful...
