### ISSUE TITLE
Button loading state does not stop on signup with taken username

### ISSUE THREAD

**Issue by binarious** [Sirimangalo/meditation-plus-angular#12]
The loading state of the signup button does not go away, when someone creates a new account and registers with a username or email which is already taken. The error message is shown, but the loading state is still active.

**Comment by olastor** [comment]
Trying to sign up with an existing username gives me an error on the server side. I think we should move this issue to the server repository.

**Comment by olastor** [comment]
Fixed with this change in `src/app/login/login.component.ts` line 85 
from
`err => this.error = err.text(),`
to
`      err => {
        this.error = err.text();
        this.loading = false;
      },`

**Comment by binarious** [comment]
Let's try fixing this with Pull Requests :). Just create a new branch (call it `fix/btn-loading-state` or something like this) for this project locally, fix the bug and push the branch. After that, GitHub offers you the option to create a Pull Request for that branch when you navigate to the project's start page.
