### ISSUE TITLE
Add list of users online

### ISSUE THREAD

**Issue by glenedharrison** [Sirimangalo/meditation-plus-angular#127]

**Comment by glenedharrison** [comment]
maybe what was referred to in #107 distinguish between questions from people who meditated recently vs. non-meditators ?

**Comment by olastor** [comment]
I'm adding your suggestions to #107 (merge them).

**Comment by yuttadhammo** [comment]
No this is actually a list of users currently viewing the app... lets us know how many people are tuned in
