### ISSUE TITLE
Archive of questions and answers

### ISSUE THREAD

**Issue by medhinidotnet** [Sirimangalo/meditation-plus-angular#128]
Hi there,

I think it would be nice to have an archive of questions asked and a link to the video the question was answered in. This way people could browse before submitting question and educate themselves. 

Just a thought.

**Comment by olastor** [comment]
Sounds like a good idea to prevent duplicate questions! We could maybe make a separate page for displaying answered questions which were answered at the time of a broadcast and link it.

**Comment by yuttadhammo** [comment]
I've been thinking about this as well... it might be nice to get transcriptions of good questions and answers and post them somewhere else... I'm not sure it would be simple or convenient within this app itself...

**Comment by olastor** [comment]
Maybe add a user group which has the permission to voluntarily add transcriptions of questions.

**Comment by olastor** [comment]
Will be handled with a **wiki**. Please reopen, if I am mistaken.
