### ISSUE TITLE
Show scheduled user names to admin

### ISSUE THREAD

**Issue by yuttadhammo** [Sirimangalo/meditation-plus-angular#130]
Right now i can't see who is scheduled, just "taken"... It would be useful to have a link to their profile on the slot they've taken

**Comment by binarious** [comment]
This is just an issue of space. Try to open the page on the computer and
make the browser window bigger. The names will show up then.

Yuttadhammo Bhikkhu <notifications@github.com> schrieb am Sa., 13. Aug.
2016 14:59:

**Comment by yuttadhammo** [comment]
Well, if i turn the phone to portrait, there's extra space... Maybe lower the threshold? I'm not often using the app on the computer

**Comment by binarious** [comment]
Ok, we could make the table scrollable. It's really taking up a lot of space when names are shown.

**Comment by yuttadhammo** [comment]
Maybe a list view instead of a table? Or being able to switch between the
two if it's not too complicated...
