### ISSUE TITLE
Make timer work on mobile phones

### ISSUE THREAD

**Issue by olastor** [Sirimangalo/meditation-plus-angular#138]
JavaScript will stop at some time to refresh the timer or play the sound when the phone is in sleep mode.

**Comment by olastor** [comment]
Possible workarounds:

- Use a sound file with length of the whole meditation session (+ bell at 2 points) and load it to play in the background ( :+1: Quite stable, displays notification on Android; :-1: Not very flexible, need to download/stream relatively big file/problematic for phones on cellular network)
- Use Google Calendar (or similar native app) and add an event (or timer) for the meditation end that will trigger an alarm (:+1: reliable, works when phone is disconnected as well; :-1: User needs to have Google account, download app)

**Comment by binarious** [comment]
Personally I'd say that we should live with the limitation for mobile users to leave the screen on until an API is provided for the thinks we want. We should add a hint for the users though. But that's just my humble opinion. What are your thoughts on that, @yuttadhammo?

**Comment by yuttadhammo** [comment]
I agree... Easier just to encourage people to use a real timer anyway
