### ISSUE TITLE
Add lying and standing meditation

### ISSUE THREAD

**Issue by medhinidotnet** [Sirimangalo/meditation-plus-angular#141]
Sometimes I'm doing standing meditation and sometimes lying. I can't log either. Would be nice to be able to do so.

**Comment by binarious** [comment]
The two formal meditation types are walking and sitting according to Bhante's teachings. Lying is an exception for people unable to sit. Don't know about the standing though. But @yuttadhammo has to decide.

**Comment by medhinidotnet** [comment]
Well, lying is sometimes necessary for people with physical issues/illnesses. It would be a shame if we support only the healthy. ;)
But in cases I have to ly down I just wont log. It's fine with me.

**Comment by yuttadhammo** [comment]
Log it as sitting meditation, since the technique is the same.
