### ISSUE TITLE
Add to homescreen

### ISSUE THREAD

**Issue by ryank85** [Sirimangalo/meditation-plus-angular#151]
is no longer working on my android phone, using most up to date version of chrome. The icon is added to desktop, but when webapp is opened, it opens in a new browser tab and not fullscreen.

**Comment by binarious** [comment]
Just tested with three different android devices. It works for me. Which version of Android are you using?

**Comment by ryank85** [comment]
4.4.4

**Comment by binarious** [comment]
Maybe this is the problem. Android 4.4 is pretty old. I've tested it successfully on Android 5 and 6. @olastor any ideas? Do you have an Android 4.4 phone to debug this?

**Comment by olastor** [comment]
This feature of Chrome seems to be in Beta and not always working as expected. Here is a fix for that

See [here](https://stackoverflow.com/questions/21018750/add-to-homescreen-button-in-android-does-not-show-website-as-a-web-app)

**Comment by olastor** [comment]
Adding this should work 

`<meta name="mobile-web-app-capable" content="yes">`

**Comment by binarious** [comment]
Done. Let's see if that works after we released the new version.
