### ISSUE TITLE
Testimonials defect on Firefox Mobile and Safari

### ISSUE THREAD

**Issue by binarious** [Sirimangalo/meditation-plus-angular#152]
![screenshot_20160815-101533](https://cloud.githubusercontent.com/assets/200375/17667244/60245644-6304-11e6-9bd9-1941b2f2c982.png)

**Comment by olastor** [comment]
@binarious  Only Firefox or Chrome as well?

**Comment by binarious** [comment]
Only Firefox

**Comment by olastor** [comment]
@binarious Would be quite difficult for me to test this on Firefox for Android. I always used [Chrome features](https://developers.google.com/web/tools/chrome-devtools/debug/remote-debugging/remote-debugging) for testing the app on Android and don't know how access this from Firefox.

**Comment by binarious** [comment]
Same error on Safari 9.1.2. 

*Error:*
> ReferenceError: Can't find variable: Intl

https://github.com/angular/angular/issues/3333

We should try https://github.com/angular/angular/issues/3333#issuecomment-203327903.

**Comment by olastor** [comment]
@binarious This is not the only issue on Firefox/Android, I suppose. Maybe we should focus on the bug in Safari, since the Firefox App can't handle the webapp as well as Chrome does.

**Comment by binarious** [comment]
I haven't heard of other problems in Firefox for Android, but yes, let's focus on Safari.
