### ISSUE TITLE
Timezone on Schedule Page

### ISSUE THREAD

**Issue by bkeevil** [Sirimangalo/meditation-plus-angular#153]
Add the Eastern Time (ET) label to the schedule page.  The monestary is located in the eastern time zone.  UTC is already labelled.

More precisely, the label could be Eastern Standard Time (EST) and switch to Eastern Daylight Time (EDT) during the summer as per the daylight savings time rules. 

From Wikipedia: "In the northern parts of the time zone, on the second Sunday in March, at 2:00 a.m. EST, clocks are advanced to 3:00 a.m. EDT leaving a one-hour "gap". On the first Sunday in November, at 2:00 a.m. EDT, clocks are moved back to 1:00 a.m. EST, thus "duplicating" one hour. Southern parts of the zone (Panama and the Caribbean) do not observe daylight saving time."

**Comment by binarious** [comment]
I'd say we should be consistent with the timezone. When we change the default to Eastern Time here, we should do it everywhere in the app. Is there any benefit in changing this? @yuttadhammo, thoughts?

**Comment by yuttadhammo** [comment]
I'd just as soon stick to utc... I know it's not perfect, but adding Eastern just makes it confusing for people in other time zones... The old app had current local time which i think was useful and may be what Bond is thinking of.

**Comment by yuttadhammo** [comment]
On the schedule page it would be good to show "your time" labels for each appointment if possible

**Comment by yuttadhammo** [comment]
Quite possibly :)

**Comment by yuttadhammo** [comment]
Yes, now i think i understand. I'd still think utc is better than eastern,
personally... Utc doesn't change.

**Comment by yuttadhammo** [comment]
On the other hand... The appointments are going to have to change along
with eastern time in November... Some maybe it would be better to base them
off that time...

**Comment by binarious** [comment]
Why do they have to change?

**Comment by yuttadhammo** [comment]
If we stay at 9pm here, then there utc time will have to change.

**Comment by binarious** [comment]
I see. We should implement this then.

**Comment by yuttadhammo** [comment]
What if we kept it at utc, but allowed admin to change the time? That might
be more useful in the long term...

**Comment by binarious** [comment]
That's already possible. You can change every single appointment. But be aware that when you change an appointment the registered user gets deregistered.

**Comment by yuttadhammo** [comment]
Ah right, that's not convenient... I guess we should just base it on
eastern time then.

**Comment by bkeevil** [comment]
Just that if you're going to display a time you also have to include the time zone or it's meaningless.  The same issue appears elsewhere, i.e. on the meditation bar graph.

AFAIK there is no consistent way of determining a user's time zone from the HTTP request.  Most CMS I am familiar with allow a user to select their time zone as part of their user profile.  By default, that time zone could be UTC.  But being able to select a local timezone in the user profile probably makes the most sense.

**Comment by yuttadhammo** [comment]
I think tz is mostly done client side... That's how the old site did it.

**Comment by binarious** [comment]
Right, JavaScript knows the browser's UTC offset which is all we need to convert times to the user's timezone in order to display them. I'd say we should display time always in the user's timezone (which is what they expect), but label it when we differ from it.

This doesn't work for stats, because the server has to calculate them. Maybe we should add a hint that the stats are based on UTC. I don't think we gain much by introducing timezones server-side other than a lot more complexity.

**Comment by binarious** [comment]
Actually I found a way which isn't that complex. Will introduce timezone configuration via https://github.com/Sirimangalo/meditation-plus-angular/issues/221.

**Comment by binarious** [comment]
@yuttadhammo Are there schedules which would switch to another day when switching between EST and EDT?

**Comment by yuttadhammo** [comment]
No, there aren't.

**Comment by binarious** [comment]
I'd like to wait for the 6th of November to see how the server behaves and fixing it then asap if necessary. Are you ok with that, @yuttadhammo?

**Comment by yuttadhammo** [comment]
Sure, that's fine
