### ISSUE TITLE
Schedule Page CSS Problem

### ISSUE THREAD

**Issue by bkeevil** [Sirimangalo/meditation-plus-angular#154]
Firefox on Windows 10.  Columns are too wide and are overflowing.

![untitled](https://cloud.githubusercontent.com/assets/2401838/17668508/93d74afa-62d7-11e6-97db-89b4fd9581d1.png)

**Comment by binarious** [comment]
Already fixed in https://github.com/Sirimangalo/meditation-plus-angular/commit/c121c48aa175c2b3a051ce1a809fd84ac2487fe9
