### ISSUE TITLE
server issues during broadcast

### ISSUE THREAD

**Issue by ryank85** [Sirimangalo/meditation-plus-angular#177]
not sure if it was just the increase in viewers, but during tonights broadcast i experienced difficulty in even loading the site, particularly the chat tab. there were also issues loading the active users box; it showed 23~ people, but when I clicked on it the list did not populate at all, it showed 0 active users

**Comment by sankhawk** [comment]
Even when sending messages, the circular progress animation keeps showing for about 5 minutes. Other sites are loading fine. So this is not a case of slow internet.

**Comment by binarious** [comment]
Hopefully has been fixed by https://github.com/Sirimangalo/meditation-plus-angular/commit/a06fef27fb7f91584f9f1cf7fc8c4b35546e53af. Feel free to reopen or create again if not.
