### ISSUE TITLE
Different timezones in meditation bar graph

### ISSUE THREAD

**Issue by bkeevil** [Sirimangalo/meditation-plus-angular#190]
It looks like the bar graph on the meditation page is recording the meditation times according to the Eastern Time Zone, such that 19:00 is when most people meditate (7pm ET).  But that the red highlighted bar is displaying the current time according to UTC.

**Comment by binarious** [comment]
Looked into that and I think you're right. The server isn't configured to UTC but to ET. The meditation dates are generated by the server and stored without the timezone information when converted into JSON for the MongoDB database. This means all meditation times need to be converted to UTC.

**Comment by bkeevil** [comment]
Also that the time zone should be labelled.  On the old site the current time was displayed prominently on the page which eliminated such confusion.  Maybe put the server time somewhere on the page?

**Comment by binarious** [comment]
> Maybe put the server time somewhere on the page?
That would be the highlighted chart bar since it's displaying the current UTC hour. I think adding "UTC" to the tooltip should resolve any confusions about it.

**Comment by binarious** [comment]
Just read this part:
> MongoDB stores times in UTC by default, and will convert any local time representations into this form. 
https://docs.mongodb.com/manual/tutorial/model-time-data/

This means that everything should be correct.

**Comment by binarious** [comment]
Can confirm that. Posted a session at 8:26pm CEST which was saved by MongoDB as `2016-08-24T18:26:59.662Z` which is 6:26pm UTC. All good. The problem occurs when retrieving the data via mongo. Then it gets converted to server time.
