### ISSUE TITLE
Timer problems

### ISSUE THREAD

**Issue by olastor** [Sirimangalo/meditation-plus-angular#191]
- alarm seems to be buggy (especially for long sessions)
- alarm will play when meditation has been stopped by user
- Bell is ringing at the beginning of the meditation on Safari

**Comment by quizasperfidia** [comment]
Recently the bell has been ringing at the beginning for me and then not ringing once the session is up. I'm using: Chrome 52.02743.98 Android 6.01.

Using how little I can feel my legs as a timer however has been quite interesting. ;)
