### ISSUE TITLE
A Means to log time without running timer

### ISSUE THREAD

**Issue by bkeevil** [Sirimangalo/meditation-plus-angular#194]
@yuttadhammo just mentioned on the broadcast that it might be useful to have a way to log time meditated without it appearing as if they are actually meditating.  It would be more honest.  So that time would be added to the user's meditation log but the timer wouldn't run. 

I think maybe a tick box next to the time entry fields labelled 'Log time already meditated'.  Or a separate 'Log' button.

**Comment by olastor** [comment]
Should there be a separation of offline vs. online meditation logs?

**Comment by binarious** [comment]
I can't think of any reason for that.

**Comment by yuttadhammo** [comment]
I was thinking just an input form to add a meditation session
retroactively, including the time and date when it took place. Maybe on the
user profile.

On Aug 19, 2016 4:53 PM, "binarious" <notifications@github.com> wrote:

I can't think of any reason for that.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Sirimangalo/meditation-plus-angular/issues/194#issuecomment-241132362>,
or mute the thread

**Comment by binarious** [comment]
I was addressing Sebastian's idea of separating these two log formats (live and retroactively) in the database. The general idea makes sense to me.

**Comment by bkeevil** [comment]
The ability to edit/delete a meditaion session that never happened would be useful too. Sometimes the phone rings or something and you can't complete the session.  So maybe just give users access to the last 10 days worth of their data table?  I'm thinking there is probably an "edit table" functionality already in this framework that would make this easy to do?

**Comment by yuttadhammo** [comment]
I dunno, that may be going a little far... there is a cancel button.

**Comment by binarious** [comment]
Actually it is a stop button. The difference is that already meditated time for this session will be logged. We could add a real cancel button which logs nothing.

**Comment by yuttadhammo** [comment]
I don't think that's a problem... The assumption is that you have been
meditating up until you press the button... If you haven't, i don't think
it's a big enough deal to make a way to remove the session entirely.

**Comment by olastor** [comment]
Where would we place the checkbox/button for that? Maybe adding a _skip timer_ button to the timer overlay would be acceptable, too?

**Comment by yuttadhammo** [comment]
Couldn't we put a form in the user profile?

**Comment by binarious** [comment]
I would prefer a form in the profile, too.

**Comment by bkeevil** [comment]
I like the idea of having something on the page that shows up while you are meditating.   A 'LOG' button next to the 'STOP' button.

**Comment by olastor** [comment]
@binarious  What input is the right one for choosing the date? Do you know if there is a working material implementation?

**Comment by binarious** [comment]
Not done yet: https://github.com/angular/material2/issues/675. Just use an input field and require a specific format. Or use multiple select fields for day, month, year, hour and minute.
