### ISSUE TITLE
Separate countdowns for walking and sitting

### ISSUE THREAD

**Issue by yuttadhammo** [Sirimangalo/meditation-plus-angular#197]
So, I actually like the fact that the UI changes once I start meditating to remind me that I should be meditating and not focusing on the app, bravo for that. But I would really like to have two timers showing, how much walking is left and how much sitting... maybe side by side? I don't think we really need the % in the middle, so maybe two circles with the time left for each on top of each, and the walking and sitting icons in the middle instead of the %?

**Comment by yuttadhammo** [comment]
The new ui is great, thank you. Just one more thing, separate minutes remaining over each circle, rather than a single minutes remaining, would be nice.

**Comment by binarious** [comment]
Thank you. We have separate circles and separate remaining minutes for walking and sitting at the moment. I don't seem to understand what this should be changed to.

**Comment by yuttadhammo** [comment]
Why do i still see a single countdown?

On Sep 3, 2016 4:33 AM, "binarious" <notifications@github.com> wrote:

Thank you. We have separate circles and separate remaining minutes for
walking and sitting at the moment. I don't seem to understand what this
should be changed to.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/Sirimangalo/meditation-plus-angular/issues/197#issuecomment-244534600>,
or mute the thread

**Comment by binarious** [comment]
Oh sorry, actually there is only one countdown. Will change that.
