### ISSUE TITLE
Integrate YouTube livestream

### ISSUE THREAD

**Issue by binarious** [Sirimangalo/meditation-plus-angular#198]
Since we need to move to YouTube for the broadcast it would be useful to integrate it on the page via https://developers.google.com/youtube/v3/live/docs/liveBroadcasts/list.
Channel ID: UCQJ6ESCWQotBwtJm0Ff_gyQ

**Comment by binarious** [comment]
Automatically reference YouTube stream with timestamp when a question gets answered (https://github.com/Sirimangalo/meditation-plus-angular/issues/222).

**Comment by olastor** [comment]
Wouldn't we need an API key from the channel broadcasting? Probably shouldn't expose such an API key on github...

**Comment by binarious** [comment]
Yes we'd need that, but we can add it to the server config which isn't hosted on GitHub.

**Comment by binarious** [comment]
@yuttadhammo Could you please create an YouTube API key with your Google Account (the same you're doing the broadcasts with)? https://developers.google.com/youtube/v3/getting-started
You can send it to me via Slack.
