### ISSUE TITLE
timer bell not taking stop input

### ISSUE THREAD

**Issue by austindmello** [Sirimangalo/meditation-plus-angular#200]
If one stops a meditation session in between for any reason, the system correctly takes the time meditated and stops the current session , however the timer alarm does not seem to take this input as it goes off  when the original time set in is up. like running a concurrent session that has actually been stopped.

**Comment by binarious** [comment]
Duplicate of https://github.com/Sirimangalo/meditation-plus-angular/issues/191.

**Comment by austindmello** [comment]
Ah ,did not see that ... Thanks ..

**Comment by binarious** [comment]
No problem. Thanks for informing us! :).
