### ISSUE TITLE
Schedule list view is a day off

### ISSUE THREAD

**Issue by bkeevil** [Sirimangalo/meditation-plus-angular#204]
Appointments on the list view tab of the schedule are showing on the wrong day.  Wednesday appointments are showing on Thursday, etc.

@yuttadhammo should probably be aware of this one.

**Comment by bkeevil** [comment]
The button to join the appointment does show up on the table view at the correct time.  I haven't tested the list view tab but will check it out this Thursday when I have my next appointment.

**Comment by milajahn** [comment]
When setting meditation time on Android, the sound goes off at the beginning of session and does not go off at the end. Thank you.

**Comment by binarious** [comment]
This has been fixed already. Please reload the app.

milajahn <notifications@github.com> schrieb am So., 21. Aug. 2016 20:16:
