### ISSUE TITLE
Give anumodana to all

### ISSUE THREAD

**Issue by binarious** [Sirimangalo/meditation-plus-angular#206]
When I enter the page I usually like to give people anumodana. Right know I'm clicking on every single one. This isn't only sometimes a lot of "work", but also increases server load when people are doing this often. Every anumodana is a server round-trip which results in a broadcast websocket message and a refresh by everyone one the page.
What do you think about "Give anumodana to all"? 

@yuttadhammo @olastor

**Comment by yuttadhammo** [comment]
Yes, it is kind of silly all that clicking... One button would be better,
with the hands close together

**Comment by binarious** [comment]
Shall we keep the single anumodana button for each session? Or just display the number without a button?

**Comment by yuttadhammo** [comment]
Maybe one button but numbers still beside each meditator?
