### ISSUE TITLE
Problem with dialog asking if I want to pose a question

### ISSUE THREAD

**Issue by bkeevil** [Sirimangalo/meditation-plus-angular#208]
I was asking a question of another user and I guess something detected the question mark and asked me if I wanted to add the tags to make it a question to Yuttadhammo.  

The dialog buttons on firefox are OK and CANCEL when they should be YES and NO

I'm not sure this feature is even that useful...

**Comment by olastor** [comment]
It will only show up once per session in order to inform new or remind old users. I don't know if the button labels can be changed that easy, but OK and CANCEL sounds quite comprehenisble to me. @binarious ?

**Comment by bkeevil** [comment]
90% of users will just click OK to an OK/Cancel dialog without reading the message.

**Comment by binarious** [comment]
This is the browser's default confirmation dialog. We can't change the buttons. They have decided that OK And Cancel work best. We will switch to Material Dialogs when they're done.
