### ISSUE TITLE
The bell is still not working (v1.2.2)

### ISSUE THREAD

**Issue by scentofwhitelotus** [Sirimangalo/meditation-plus-angular#209]
When I start a meditation session the bell rings at the beginning. I use the google chrome brower on Android.

**Comment by binarious** [comment]
I have experienced this, too. @olastor, ideas?

**Comment by olastor** [comment]
I can't reproduce the error... Does the ring only at the beginning or when walking/sitting is over as well? Is your Android newer than 4.4?

**Comment by scentofwhitelotus** [comment]
I use a Samsung S3 with the customROM Cyanogenmod, Android 4.4.
The bell does only ring at the beginning.

**Comment by binarious** [comment]
Cyanogenmod Android 5 on my backup phone. Can test with my regular Android 6 (Stock ROM) tomorrow.

**Comment by bkeevil** [comment]
I reproduced this.  Chrome on Android 4.4.2

**Comment by olastor** [comment]
Made a little test snippet at http://olastor.github.io/. Can you test on your devices if the bell rings before the countdown is at 0 @bkeevil @binarious @scentofwhitelotus ?

**Comment by scentofwhitelotus** [comment]
Both timers work on my phone.

**Comment by binarious** [comment]
Both work for me as well.

Paul <notifications@github.com> schrieb am Mi., 24. Aug. 2016 14:31:

**Comment by binarious** [comment]
I think the second implementation is the way to go since the first one throws this error/warning: 
```
undefined:1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().
```

**Comment by bkeevil** [comment]
Both work for me

**Comment by binarious** [comment]
The current timer implementation on meditation.sirimangalo.org worked perfectly fine on my Android 6 device with Chrome 52.0.2743.98. What Chrome version were you using @bkeevil @scentofwhitelotus and @olastor? I think it's a limitation of older Android versions we need to live with.

**Comment by scentofwhitelotus** [comment]
@binarious Today the bell ringed at the beginning and at the and. My current chrome version is 52.0.2743.98 but I don't know when the last update was so the bug could have been because chrome had some issues.

**Comment by olastor** [comment]
It doesnt always work for me, either. I'll check it out and maybe change the module (again).

**Comment by binarious** [comment]
Still works for me. The bell is ringing at the beginning when one does sitting only.
