### ISSUE TITLE
WebRTC

### ISSUE THREAD

**Issue by binarious** [Sirimangalo/meditation-plus-angular#21]
Replace the hangout implementation of the appointments with own WebRTC setup.

**Comment by binarious** [comment]
@olastor Do you find time to do a little research? I haven't worked with WebRTC and didn't found an easy solution. Most libraries are dead. I think we need our own STUN and TURN servers, but I'm not sure about that.

**Comment by olastor** [comment]
Seems to be not needed right now. Please reopen if I'm wrong.

**Comment by binarious** [comment]
@yuttadhammo Please let us know if you still need this.

**Comment by yuttadhammo** [comment]
It would be nice... We don't really have a solid video conference platform
for interviews... Google is acting weird with its messaging apps. If we
could create a platform for video interviews tied in to the schedule, that
would be really useful.

On Apr 21, 2017 12:21 PM, "binarious" <notifications@github.com> wrote:

@yuttadhammo <https://github.com/yuttadhammo> Please let us know if you
still need this.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Sirimangalo/meditation-plus-angular/issues/21#issuecomment-296236642>,
or mute the thread

**Comment by olastor** [comment]
@binarious I looked a bit into it. STUN and TURN server don't use http, so we have to install them seperately on the server (a good ressource seems to be https://github.com/coturn/coturn). WebRTC itself works peer-to-peer (except for the fallback to the TURN server), they only need to exchange some network data for calling and answering (could use socket.io for that).

Useful links:
- http://io13webrtc.appspot.com
- https://codelabs.developers.google.com/codelabs/webrtc-web
- https://www.html5rocks.com/en/tutorials/webrtc/infrastructure/

**Comment by seyuf** [comment]
Hi, actually i have done webrtc in the past. 
You don't necessarily need to host a  STUN server, i believe there are a lot of free ones out there.
In the past i've used the one provided by google it worked just fine stun:stun.l.google.com:19302.
You could use that for a start. 
[useful link](https://gist.github.com/zziuni/3741933)

🙏  ☮️

**Comment by olastor** [comment]
@seyuf Thanks for the Info! What about the TURN server as a fallback for when STUN ist not supported by the client? Are they necessary? We could consider showing the gooogle Hangouts link as a fallback instead.

**Comment by seyuf** [comment]
The turn server is not really needed. It's supposed to cover cases where the client is behind a firewall and stuff. But in reality, the STUN protocol is largely sufficient for NAT topology discovery behind most firewalls. [Not needed but if you want to know how it works](https://webrtchacks.com/stun-helps-webrtc-traverse-nats/).

**Comment by olastor** [comment]
@seyuf I am trying to set something up for this. Would you find the time to review it afterwards or work together on this? I took a look at https://github.com/feross/simple-peer which seems to be an easy to use and well maintained package, do you have any other tips?

**Comment by seyuf** [comment]
@olastor, i will try to publish on my Github a full example in angular 1 this weekend. You could check that out.

**Comment by olastor** [comment]
@seyuf I made it work with https://github.com/feross/simple-peer . Your example would probably be useful, but please don't publish it, if it consumes much time.

**Comment by seyuf** [comment]
@olastor Alright, i just published my example :).  
You can check it out at https://github.com/seyuf/WebRTC.
The angular app will be at https://github.com/seyuf/WebRTC/tree/master/app/assets/javascripts.

:peace_symbol: :pray:
