### ISSUE TITLE
Unable to stop meditation countdown

### ISSUE THREAD

**Issue by medhinidotnet** [Sirimangalo/meditation-plus-angular#210]
Hi there,

Accidentally I hit the timer button on tab Meditation. Meant to hit the question only button on tab Chat.
Now I can't undo the countdown which makes it seem that I'm meditating while I'm not.

I use Chrome, version 52.0.2743.116 (64-bit).

However, on my iPhone stopping the countdown does work.

**Comment by binarious** [comment]
I can't reproduce the error. Could you please refresh your app and retry it a second time?
But this time open the Developer Console, please (On OS X: cmd + alt + j, on Windows/Linux: ctrl + shift + j). Paste anything that's displayed in the console into this issue.

**Comment by medhinidotnet** [comment]
Hope this is good enough

![screen shot 2016-08-24 at 20 56 41](https://cloud.githubusercontent.com/assets/20887392/17943521/0a87058a-6a3c-11e6-9196-e92ddcccbe53.png)

**Comment by binarious** [comment]
Thanks. This seems to be a bug in a browser extension you're using. Please disable them and retry. Feel free to reopen if that doesn't resolve the problem.
