### ISSUE TITLE
Questions and 100 messages limit

### ISSUE THREAD

**Issue by binarious** [Sirimangalo/meditation-plus-angular#213]
The client only loads the last 100 messages to reduce cpu load. This limitation applies to the questions only mode, too. So if there is an unanswered question 101 messages (not questions) back, it would not be shown. We should do a separate server-side filtering for questions.

/cc @yuttadhammo @olastor

**Comment by yuttadhammo** [comment]
What if we moved the questions out of the chat, replaced the commitments with them, and allowed users to vote on the questions? Commitments could go in the menu.

**Comment by olastor** [comment]
We could also store the time a question has been answered and find a way to automatically generate a link to the related broadcast video (maybe with the correct time within the video as well).

**Comment by medhinidotnet** [comment]
Does this mean the wiki becomes obsolete?

See also: 
https://github.com/Sirimangalo/meditation-plus-angular/issues/128

**Comment by olastor** [comment]
No, as far as I know the wiki is still in place.

**Comment by binarious** [comment]
Closed in favor of https://github.com/Sirimangalo/meditation-plus-angular/issues/222.
