### ISSUE TITLE
Ability to mark own question as answered and/or remove as question

### ISSUE THREAD

**Issue by binarious** [Sirimangalo/meditation-plus-angular#214]

**Comment by olastor** [comment]
Maybe we should combine this and #213 ('question tab') and add all features to a list. Feel free to add/change/move/delete:

- [ ] Change 'Commit' tab with new 'Questions' tab, move 'Commits'  to Navbar
- [ ] Increase number of questions displayed (not only from chat history)
- [ ] Add ability to mark own question as answered and/or remove as question
- [ ] Add ability to vote for questions
- [ ] Add feature for linking live broadcasts for questions marked at answered at this time

**Comment by binarious** [comment]
Closed in favor of https://github.com/Sirimangalo/meditation-plus-angular/issues/222.
