### ISSUE TITLE
Time of walking and sitting is mixed up when a session has been stopped (finished list) 

### ISSUE THREAD

**Issue by olastor** [Sirimangalo/meditation-plus-angular#218]
Problem lies here (I think): https://github.com/Sirimangalo/meditation-plus-server/blob/master/src/app/routes/_meditation.router.js#L174
Waiting for #217 to be merged

**Comment by binarious** [comment]
Yep, problem is in https://github.com/Sirimangalo/meditation-plus-server/blob/master/src/app/routes/_meditation.router.js#L175. Sitting needs to be reduced first. Feel free to open a pull request on the server-side, since it's not conflicting with the angular upgrade.
