### ISSUE TITLE
Improve tabless layout (prevent multiple scrollbars)

### ISSUE THREAD

**Issue by olastor** [Sirimangalo/meditation-plus-angular#220]

**Comment by binarious** [comment]
How? I don't know if we should put much time in this alternative layout. It's nice to have this option to get an overview, but maintaining two optimized layouts is going too far in my opinion. @yuttadhammo, thoughts?

**Comment by olastor** [comment]
Yes, let's deal with the important stuff first. I thought about adding a scroll effect.

**Comment by yuttadhammo** [comment]
I haven't used the tabless layout... How do i access it? I don't mind the default layout, no need for two distinct layouts, i don't think?

**Comment by binarious** [comment]
Profile -> Checkbox "Alternative layout".

**Comment by yuttadhammo** [comment]
Yeah, i think we can get rid of that, personally...
