### ISSUE TITLE
Show times in hours, not days

### ISSUE THREAD

**Issue by yuttadhammo** [Sirimangalo/meditation-plus-angular#225]
I think it's probably not so useful to tell people how many days worth of meditation has been practiced... At least in English, this sounds strange. I think "100 hours" of meditation is more informative than "four days", no?

**Comment by binarious** [comment]
Personally I prefer `350 days` over `8400 hours`, but we could change it to hours. Just need to check how to integrate this. Currently it's just the output of moment.js's `humanize()` function.

**Comment by yuttadhammo** [comment]
In English, "two days worth of meditation" means more like two days where
you meditated normally, rather than two whole 24 hour periods worth of
meditation, i think...

**Comment by binarious** [comment]
Fair point. Will look into it.

**Comment by binarious** [comment]
Closed by https://github.com/Sirimangalo/meditation-plus-angular/pull/262.
