### ISSUE TITLE
Popup hints on "Submit a Question" buttons

### ISSUE THREAD

**Issue by bkeevil** [Sirimangalo/meditation-plus-angular#240]
I can mark my own question as answered.  Is this intended behavior?  And its not clear that the check mark button means 'Mark as Answered'.  Maybe add popup hints to those buttons?

**Comment by binarious** [comment]
It's intended since one can find the answer afterwards. Maybe the delete button is enough for that, but I thought it would be nice to enable it. Tooltips should be added, right.
