### ISSUE TITLE
Add rules to the ask tab

### ISSUE THREAD

**Issue by binarious** [Sirimangalo/meditation-plus-angular#256]

**Comment by CittaV** [comment]
(These are the rules that I remember Bhante had said or something like it, so sorry if I'm wrong)
Rule 1: Do not ask questions that Bhante doesn't know, or is out of his field, such as what do you think of some person 

Rule 2: Do not ask speculative question (or sometimes things that doesn’t have to do with meditation)

Rule 3: Do not ask about Yuttadhammo, such as about his experiences, or if he is enlightened, etc.

**Comment by medhinidotnet** [comment]
First: I think we should ask Bhante about this.
Second: I also think that we shouldn't impose any rules on asking questions. Instead I suggest 'Friendly or Helpful Reminders'.
What these are should be up to Bhante @yuttadhammo  .

**Comment by binarious** [comment]
Right, these rules come from @yuttadhammo. They've been rephrased and integrated in the changeset https://github.com/Sirimangalo/meditation-plus-angular/pull/257 which is waiting for his review.

**Comment by yuttadhammo** [comment]
Maybe like this:

Please do not ask questions about other religious or spiritual practices
unrelated to our tradition.

Please do not ask questions that are speculative or unrelated to Buddhist
practice in general.

Please do not ask questions about the personal experiences or attainments
of others.
