### ISSUE TITLE
Activate account via email

### ISSUE THREAD

**Issue by binarious** [Sirimangalo/meditation-plus-angular#28]
An account should be activated via email. It's currently enabled by default.

**Comment by doksu** [comment]
I think this is probably the most important outstanding issue.

**Comment by yuttadhammo** [comment]
why is this important?

**Comment by binarious** [comment]
@yuttadhammo To mitigate spam/fake user creation.
@doksu Can you install a smtp server? We also need it for #27.

**Comment by binarious** [comment]
@doksu any news since we moved to a new provider?

**Comment by olastor** [comment]
@binarious Can we use [Nodemailer](https://github.com/nodemailer/nodemailer) for this?

**Comment by binarious** [comment]
Yes, please.
