### ISSUE TITLE
Automating broadcast start and stop announcement

### ISSUE THREAD

**Issue by yuttadhammo** [Sirimangalo/meditation-plus-angular#289]
Would there be some way to tie in the broadcast start and stop in the app to the icecast broadcast? It runs a bash script on the server when it starts and when the audio broadcast starts and stops, so it would  save me having to push yet another set of buttons. Just a thought, not urgent though.

**Comment by olastor** [comment]
Locally, this works for me (to send a POST request to start a broadcast)

```
#!/bin/bash

email="neu@neu.de"
password="123456789"
token=$(curl --silent --data "email=${email}&password=${password}" http://localhost:3002/auth/login | grep -oP '[^"]{35,}')
now=$(date +%FT%H:%M:%SZ)

curl -H "Authorization: Bearer ${token}" --data "started=${now}" http://localhost:3002/api/broadcast
```

@binarious Is this a proper request? Does not work for `https` yet.

**Comment by binarious** [comment]
@olastor Good idea, this would work, but it would also require to have a password in cleartext in the bash script.
I rather would like to invest some time and implement a solution with the more complex YouTube API.

**Comment by binarious** [comment]
The OAuth version of the YouTube API, which is required to get live broadcast data, seems to require a user to login to YouTube. I think we should go for the icecast script.

- create a cli command that starts a new broadcast (triggered by icecast start)
- create a cli command that ends the last broadcast and polls YouTube for the latest video until it's there (maybe for max. 1 hour) (triggered by icecast stop)

Thoughts?

**Comment by olastor** [comment]
@yuttadhammo Does the icecast script run on your OS locally or on the server (when you start the broadcast).

**Comment by yuttadhammo** [comment]
It's on the server, Doug migrated it over from the old server. It creates a
time stamp on start and then normalizes and tags the dumped audio for
archiving on end.
