### ISSUE TITLE
Display Name

### ISSUE THREAD

**Issue by doksu** [Sirimangalo/meditation-plus-angular#30]
It would be nice if the user could have a display name that's different from their username.

**Comment by yuttadhammo** [comment]
Sounds reasonable... Can't think of a purpose for the username

**Comment by yuttadhammo** [comment]
Unless someone wanted to change the email associated with their account...

**Comment by binarious** [comment]
Event that would be possible without a username after #28 is done. So I'll remove the username and add a generic name field.
