### ISSUE TITLE
Countdown display broken

### ISSUE THREAD

**Issue by yuttadhammo** [Sirimangalo/meditation-plus-angular#313]
On mobile, the app played a sound before the timer was finished, and when i looked, it showed this screen:

![tmp_25673-screenshot_20161001-2023561595479165](https://cloud.githubusercontent.com/assets/143189/19024663/0b1566e6-88d6-11e6-8d7d-4c3df5ef4f90.png)

**Comment by binarious** [comment]
Relates to https://github.com/Sirimangalo/meditation-plus-angular/issues/300.

**Comment by bkeevil** [comment]
Yeah on android the bell seems to play at random times, if at all.

**Comment by olastor** [comment]
I think `<md-progress-circle>` is not correctly updating if the value is 0 somehow.
