### ISSUE TITLE
page not responsible after beeing in background for some time 

### ISSUE THREAD

**Issue by olastor** [Sirimangalo/meditation-plus-angular#323]
Can't switch tab or open sidenav, even though the url changes to `;tab=tabname`. Site is still doing the subscribed `GET` requests. Is this a firefox thing?

**Comment by binarious** [comment]
There is currently a bug in ng2-charts that freezes the app after an hour.
Will be fixed after the new update.

Sebastian K. <notifications@github.com> schrieb am So., 9. Okt. 2016, 21:19:

**Comment by binarious** [comment]
Let's reopen this issue if the release does not fix it.
