### ISSUE TITLE
Chat scrollbar overflow not properly working in Firefox

### ISSUE THREAD

**Issue by olastor** [Sirimangalo/meditation-plus-angular#34]
Scrollbar should only appear in the chatbox (`y-overflow`). In Firefox, the box grows and enables the window scrollbar.

![Screenshot here](https://cloud.githubusercontent.com/assets/7479641/17328481/4a910214-58be-11e6-9697-8ff985101dac.png) 
left: Firefox 47 on Ubuntu GNOME (Bug)
right: Chromium (working)

**Comment by binarious** [comment]
It works here: https://jsfiddle.net/LmYay/1027/. So there may be an error in our css classes.

**Comment by olastor** [comment]
Applying `min-height: 0;` to `<message>` changes something. Now the body is only 64px too big (the size of the 'Meditation+' header or the panel below). Maybe it's [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1043520)

**Comment by olastor** [comment]
Changing the `flexbox-item-grow` class in [`src/app/app.css`](https://github.com/Sirimangalo/meditation-plus-angular/blob/fix/firefox-bug/src/app/app.css) from

`.flexbox-item-grow {
  -webkit-flex: 1;
  flex: 1;
}`

to

`.flexbox-item-grow {
  -webkit-flex: 1;
  flex: 1 1 auto;
}
`

worked for me. I wonder why (it should be the same, since the default is `0 1 auto`)? @binarious @bkeevil If this works on your machines to, we can probably close this issue.

**Comment by binarious** [comment]
Ah right, read about this issue some weeks ago. Totally forgot about it. Great find. Could you please create a pull request from your branch?
