### ISSUE TITLE
Switch to yarn

### ISSUE THREAD

**Issue by binarious** [Sirimangalo/meditation-plus-angular#346]
https://yarnpkg.com/
Direct replacement of npm: https://yarnpkg.com/en/docs/migrating-from-npm

**Comment by binarious** [comment]
Let's wait until Travis supports it: https://github.com/travis-ci/travis-ci/issues/6720

**Comment by binarious** [comment]
@Daniel15 Thanks for letting us know. Doesn't this remove the performance benefit?

**Comment by Daniel15** [comment]
If you install a lot of npm packages (or have a very deep dependency tree), Yarn should still improve perf if you configure Travis to cache the Yarn cache directory, even with the overhead of installing it as part of the build. I hope eventually Travis will preinstall Yarn on their build servers - AppVeyor already does that :)

**Comment by binarious** [comment]
Great, thank you for your effort getting this into Travis.

**Comment by binarious** [comment]
I'm still seeing a `npm install` section in the build: https://travis-ci.org/Sirimangalo/meditation-plus-angular/jobs/176813033#L301

**Comment by binarious** [comment]
Done in df421a8d27ab7a9fdc0aab103ed72a3785cc6540.
