### ISSUE TITLE
Schedule page table & list views don't show the day-of-week correctly

### ISSUE THREAD

**Issue by parthopdas** [Sirimangalo/meditation-plus-angular#351]
Here is the view with my TZ set to Sydney time:
![image](https://cloud.githubusercontent.com/assets/2140460/20287622/844e2494-aa9b-11e6-9412-3a064a2e86af.png)

Here is the view at the same time with timezone changed to Toronto:
![image](https://cloud.githubusercontent.com/assets/2140460/20287584/5b4c322a-aa9b-11e6-9567-8b06f5425045.png)

Consider my slot on Tuesday at 18.30 EST, which is in Toronto TZ.
From Sydney, it shows the slot at Tuesday 10.30 am. It should really be Wednesday 10.30 am.

**Comment by binarious** [comment]
Thanks for reporting. Seems to have been introduced in via #153. @olastor do you have time to look into this?

**Comment by parthopdas** [comment]
If this can wait till 20th of Dec, I can pick it up then.

**Comment by olastor** [comment]
@parthopdas Will fix it together with #354 #355 soon

**Comment by binarious** [comment]
Should be addressed with https://github.com/Sirimangalo/meditation-plus-angular/commit/86446c48046c367ea711763721315db50dfd2d12.
