### ISSUE TITLE
Edit box border issues in Firefox 47.0

### ISSUE THREAD

**Issue by bkeevil** [Sirimangalo/meditation-plus-angular#36]
Not sure if this is an intentional design decision or not.  I found it hard to find the edit boxes because they only have a bottom border.  See screenshot and the copy of the computed CSS properties.

![displayissue](https://cloud.githubusercontent.com/assets/2401838/17350314/96ffee64-58f3-11e6-9e86-c57784698db7.png)
[computed.txt](https://github.com/Sirimangalo/meditation-plus-angular/files/398450/computed.txt)

**Comment by binarious** [comment]
That's Google's design decision in Material Design: https://material.google.com/components/text-fields.html#text-fields-labels
We follow the Material Design guidelines. If you have an idea to improve this then please let us know. Having a full border breaks the idea of floating labels.
