### ISSUE TITLE
Double scroll bar on chat window

### ISSUE THREAD

**Issue by bkeevil** [Sirimangalo/meditation-plus-angular#37]
This double scroll bar on the right of chat window.   Firefox 47.0 on Windows 10.

Looks like <div class="flexbox-item-grow" ...> calculating the wrong height or something.  Not sure about how that works.  Let me know if you need me to inspect CSS properties.

![doublescroll](https://cloud.githubusercontent.com/assets/2401838/17350631/6471a94e-58f6-11e6-91f9-66edf597c445.png)

**Comment by binarious** [comment]
Same as https://github.com/Sirimangalo/meditation-plus-angular/issues/34
