### ISSUE TITLE
Edit field titles on profile form

### ISSUE THREAD

**Issue by bkeevil** [Sirimangalo/meditation-plus-angular#38]
The edit field titles on the profile form.  The title for the username field is "Description" and the field to enter the country does not have a visible title.

![editfieldtitles](https://cloud.githubusercontent.com/assets/2401838/17350773/8ba18e16-58f7-11e6-9c2e-89eedaad2cdf.png)

**Comment by binarious** [comment]
The username is not editable. This really is the description. The select component of Angular2 material is not ready, yet. That's the reason of the missing label for country. We're waiting for it: https://github.com/angular/material2/issues/118

**Comment by binarious** [comment]
Done via https://github.com/Sirimangalo/meditation-plus-angular/commit/36c1fd8726268b3709c358e4ff2a7d8928502dd4. Label workaround until the material select components are ready.
