### ISSUE TITLE
webpack.validateSchema is not a function

### ISSUE THREAD

**Issue by olastor** [Sirimangalo/meditation-plus-angular#398]
getting a local error when running `npm run start:hmr`

Changing https://github.com/Sirimangalo/meditation-plus-angular/blob/master/package.json#L162

to `"webpack-dev-server": "2.1.0-beta.9",` fixed it somehow

See: https://github.com/AngularClass/angular2-webpack-starter/issues/1174

Edit: Didn't work:
``
[default] /home/sebastian/Dokumente/Code/meditation-plus-angular/node_modules/@angular/forms/src/version.d.ts:13:10 
    Module '"/home/sebastian/Dokumente/Code/meditation-plus-angular/node_modules/@angular/core/index"' has no exported member 'Version'.
[default] Checking finished with 1 errors
``

**Comment by binarious** [comment]
I think we need to synchronize with the angular2-webpack-starter repo.
Last update was done on git hash a862b28.
Therefore this are the changes. 
https://github.com/AngularClass/angular2-webpack-starter/compare/a862b28...master

**Comment by binarious** [comment]
Closed via df421a8d27ab7a9fdc0aab103ed72a3785cc6540.
