### ISSUE TITLE
Commitment for 840 min weekly meditation not calculated correctly

### ISSUE THREAD

**Issue by FernandoDelta** [Sirimangalo/meditation-plus-angular#401]
The commitment for 840 min of weekly meditation is not being calculated correctly. I believe this started after the new year when data of 2016's weeks is displayed with data of 2017's weeks. I should have 100% in that commitment and the app says it is only 64%.

Thanks.

**Comment by olastor** [comment]
@FernandoDelta Did it word correctly before the last release 3 days ago? Or did it start at new year?

**Comment by FernandoDelta** [comment]
Hi,

It was not caused by the last release. I believe it started at new year.

Fernando

**Comment by bkeevil** [comment]
This bug existed last fall.

**Comment by binarious** [comment]
@FernandoDelta Do you still see the wrong numbers this week with your current data?

**Comment by FernandoDelta** [comment]
Yes. I see only 64% of the 840 min commitment. Screenshots of my profile
and commitment pages are attached.


​

**Comment by olastor** [comment]
It may be because of your timezone. Would you please tell US what timezone you're in?

**Comment by binarious** [comment]
@olastor If his profile stats are showing the correct data (I can't tell since I don't see his attachments), then it should work for the calculation since we use the same data for that.

**Comment by FernandoDelta** [comment]
My timezone is UTC-6. Guadalupe has the same problem and the same timezone, with only 64% in the 840 min commitment. Here is another picture of my profile stats with my user name. It seems that the commitment percentage is considering only 540 min in the average of the ten days.
![profile2](https://cloud.githubusercontent.com/assets/20957691/22787054/8ddac2e4-eea0-11e6-9fc1-e8cc0b02e248.png)

**Comment by FernandoDelta** [comment]
I tried the other commitments (400 min and 500 min), just to see what happens, and the percentages shown correspond to a weekly meditation time of 540 min when I should have 780 min (at the time I checked).

**Comment by FernandoDelta** [comment]
I believe that I know what's the problem. The app takes the amount of minutes of the last bar shown in the histogram of "Last 10 weeks"  that for me is 540 but since new year the last bar is not the current week because new weeks started from left to right substituting weeks of last year instead of displacing the old ones from right to left. For example the histogram I have in my profile has the weeks the following order: 1 2 3 4 5 6 50 51 52 53 where 1 2 3 4 5 and 6 are more recent than 50 51 52 53. The correct order would be 50 51 52 53 1 2 3 4 5 6.

**Comment by olastor** [comment]
@FernandoDelta Thanks for the hint! I fixed it here https://github.com/Sirimangalo/meditation-plus-server/pull/123 . It'll be fixed on the website soon (I hope). I'm closing this issue now, feel free to reopen, though.
