### ISSUE TITLE
Push Notifications API 

### ISSUE THREAD

**Issue by olastor** [Sirimangalo/meditation-plus-angular#403]
- optional instead of meditation bell on phones
- for messages with mentioning
- for notification about update (?)

**Comment by olastor** [comment]
@binarious Do you have a specific idea how to do this?

**Comment by binarious** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Push_API/Using_the_Push_API

Sebastian K. <notifications@github.com> schrieb am Do., 23. Feb. 2017,
09:12:

**Comment by olastor** [comment]
GCM API Key needed (see http://stackoverflow.com/questions/41827156/can-we-do-web-push-notifications-in-chrome-without-using-gcm-fcm). Shouldn't be a problem, though.

**Comment by binarious** [comment]
It's now called FCM:
https://firebase.google.com/docs/cloud-messaging/
https://firebase.google.com/docs/cloud-messaging/js/client

I don't know what to do for iOS though.

**Comment by olastor** [comment]
We'd need an Apple Developer Account and https://github.com/node-apn/node-apn . But I can't implement it, because I don't have Safari.

**Comment by olastor** [comment]
closed via #418
