### ISSUE TITLE
[Admin] Broadcast interface redundant

### ISSUE THREAD

**Issue by olastor** [Sirimangalo/meditation-plus-angular#407]
The feature for saving the time of a broadcast hasn't been used since 2016-11-09. It was thought to save the time a question has been answered to get the correct time within the youtube video of the broadcast. We could replace it with a script that only finds the source (audio link, youtube video) of a question that has been answered during a broadcast and get rid of the broadcast interface and the button for starting answering a question.

@yuttadhammo @binarious

**Comment by binarious** [comment]
Personally I find it useful to have the exact timecode to the video section. Otherwise people would have to watch a 1 hour long video to find an answer to their specific question. @yuttadhammo why did you stop using this feature? Can we maybe improve things to make it easier to use?

**Comment by yuttadhammo** [comment]
The broadcast software was broken for Linux, memory leak, so i stopped
using YouTube live. Hopefully it's fixed soon or already... I'll try again
when i get back from New York.
