### ISSUE TITLE
can't login via my mobile

### ISSUE THREAD

**Issue by meditator3** [Sirimangalo/meditation-plus-angular#412]
hi,
somehow my login says unauthorized.
and there is no way to recreate a password?
the siri website works via my desktop computer

**Comment by olastor** [comment]
Does your password work on desktop? Then the password is probably not the problem, if it worked before on your phone and you tried to login with it. What operating system (Android, IOS) and what browser (Chrome, Safari, Firefox) are you using on your mobile?

**Comment by meditator3** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } I am afraid to try it in case I get locked in. At my desktop computer. 
I'm using latest iOS I think 10 or 11. On safari 


Sent from Yahoo Mail for iPhone


On Monday, March 6, 2017, 11:15 AM, Sebastian K. <notifications@github.com> wrote:


Does your password work on desktop? Then the password is probably not the problem, if it worked before on your phone and you tried to login with it. What operating system (Android, IOS) and what browser (Chrome, Safari, Firefox) are you using on your mobile?

**Comment by olastor** [comment]
Ok, when you're not sure what your password is, then you can change it as long as your logged in and try logging in with the new password on your phone. If you somehow lock yourself out of your account, just tell us/one of the admins in chat, we can always reset your password.

**Comment by meditator3** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Yes!It worked! That's what triggered it in the first place. I guess I tried to update my bell and then forgot to update password upon updating the profile. Or maybe I messed up the password there too. 
Thanks man


Sent from Yahoo Mail for iPhone


On Monday, March 6, 2017, 1:08 PM, Sebastian K. <notifications@github.com> wrote:


Ok, when you're not sure what your password is, then you can change it as long as your logged in and try logging in with the new password on your phone. If you somehow lock yourself out of your account, just tell us/one of the admins in chat, we can always reset your password.
