### ISSUE TITLE
Improve Performance

### ISSUE THREAD

**Issue by olastor** [Sirimangalo/meditation-plus-angular#420]
- [ ] Remove the use of the shadow-Piercing descendant combinator (`/deep/`) since it has a bad performance impact (we're using it a lot).
- [ ] Lazy load bigger modules (especially the admin section)
- [ ] Use ngrx (to make components dumb and force `OnPush`)
  - [x] messages (https://github.com/Sirimangalo/meditation-plus-angular/pull/562)
  - [ ] meditation
  - [ ] question
  - [ ] profile
  - [ ] login
  - [ ] testimonial
  - [ ] commitment
  - [ ] appointment
- [ ] Switch to rxjs's [lettable operators](https://github.com/ReactiveX/rxjs/blob/master/doc/lettable-operators.md)
- [ ] Make use of server-side rendering or the Application Shell.

**Comment by binarious** [comment]
Ideas:
- Remove the use of the shadow-Piercing descendant combinator (`/deep/`) since it has a bad performance impact (we're using it a lot).
- Lazy load every module.

**Comment by binarious** [comment]
https://github.com/mgechev/angular-performance-checklist
^ That's what we need 🙂

**Comment by binarious** [comment]
Moved to https://gitlab.com/sirimangalo/meditation-plus/issues/15
