### ISSUE TITLE
Reintroduce usernames

### ISSUE THREAD

**Issue by binarious** [Sirimangalo/meditation-plus-angular#422]
Needed for https://github.com/Sirimangalo/meditation-plus-angular/issues/58 and it's useful in general. 
Ideas:
- We should ask for the username on the first login and invalidate every session without a username.
- Usernames shouldn't be allowed to change (for mentions).

**Comment by olastor** [comment]
I am currently working on an autocomplete that works with the present name Format. It would store the id of users mentioned in a separate property in the message model. I'll try to finish it soon

**Comment by binarious** [comment]
I thought about that, too, but I think it will be problematic with multiple mentions in combination with the normal use of an `@`. How do you want to handle this?

**Comment by olastor** [comment]
I don't think that's a problem. The suggestion box would open when typing `@`, but also close if the text afterwards doesn't match a user's name. A mention will be only added if actively selected (enter, tab or click) through the suggestions box. Then when displaying the message, any occurence of '@' + the user's name will be replaced with a reference to the profile page. I'll try to open a PR soon, then we can discuss more and decide which way is better.

**Comment by olastor** [comment]
Do you have a specific username format in mind (like only lower case letters and no spaces `name_surname`) or just make the current names unique?
