### ISSUE TITLE
Passwort reset doesn't work

### ISSUE THREAD

**Issue by binarious** [Sirimangalo/meditation-plus-angular#423]
I've just clicked on "Forgot Password":
```
Error: Uncaught (in promise): TypeError: Cannot read property 'length' of undefined
```
Minified position:
```js
, t = !e.success && (0 === e.userId.length || 0 === e.token.length);
```
Must have been [this commit](https://github.com/Sirimangalo/meditation-plus-angular/pull/421/commits/a23c33c9cd06a2f76ef2241aefd0f591b43d33e1).

**Comment by olastor** [comment]
I changed that because the travis test wouldn't work: https://travis-ci.org/Sirimangalo/meditation-plus-angular/builds/224596213#L355
