### ISSUE TITLE
TODOs on server for release 1.10.0

### ISSUE THREAD

**Issue by olastor** [Sirimangalo/meditation-plus-angular#435]
- [x] Intensive testing on DEV server
- [x] `db.users.dropIndex('username')` (reason: https://github.com/Sirimangalo/meditation-plus-server/pull/136)
- [x] Set verified property of existing users to **true**: 
COMMAND: `db.users.updateMany({}, {$set: { verified: true }})`
- [x] Add `src/scripts/push-cleanup.js` to CRON
- [x] Manually set reserved usernames
- [x] Set API keys

\* mongo commands only work for version >= 3.2
\* make sure to tab into the DB first with `use meditation-plus`

**Comment by binarious** [comment]
Can you Doug to add the cron entry?
