### ISSUE TITLE
Can't login - username requirement on the login page

### ISSUE THREAD

**Issue by alex3kov** [Sirimangalo/meditation-plus-angular#447]
![login_username](https://cloud.githubusercontent.com/assets/3616242/26028836/b592fb9c-3830-11e7-86d4-852cbcc72ed9.png)

How do I set a username without logging in?

**Comment by binarious** [comment]
Please reload the app (or clear you browser cache). You're using an old version of the app.

**Comment by alex3kov** [comment]
Clearing browser cache helped - login page said something about reloading webpage to update app (what app? I'm just using a desktop browser) and then let me set the username.

**Comment by binarious** [comment]
Glad that it worked 🙂. Complex websites are now called (web) apps, too.
