### ISSUE TITLE
Opening chat message menu overlay makes app slow

### ISSUE THREAD

**Issue by binarious** [Sirimangalo/meditation-plus-angular#449]

**Comment by binarious** [comment]
Let's first try upgrading Angular Material (https://github.com/Sirimangalo/meditation-plus-angular/issues/508).

**Comment by binarious** [comment]
Still the case after the upgrade. Maybe we should create a small test case to reproduce this outside of our app.

**Comment by olastor** [comment]
@binarious Maybe we could avoid this bug by adding a little settings button to own messages instead of using touch events?
