### ISSUE TITLE
Long title pushes online icon outside window (style)

### ISSUE THREAD

**Issue by olastor** [Sirimangalo/meditation-plus-angular#483]

**Comment by binarious** [comment]
Do you have an example?

**Comment by olastor** [comment]
On the meditation screen when the screen size is lower than ~400px

![bildschirmfoto vom 2017-11-27 um 09 51 02](https://user-images.githubusercontent.com/7479641/33258015-8a967770-d358-11e7-8b88-7572b6ae2bf5.png)

**Comment by binarious** [comment]
Moved to https://gitlab.com/sirimangalo/meditation-plus/issues/13
