### ISSUE TITLE
Add explanation on the bar chart in meditation tab

### ISSUE THREAD

**Issue by jiixing** [Sirimangalo/meditation-plus-angular#490]
I think this is the total recorded meditation on the previous hours?

The information seems superfluous to me, I suggest it is hidden by a toggle or moved to a statistic page?

A separate page can show other stats like total meditation hour per date

**Comment by olastor** [comment]
The site looks quite empty without the chart if there are no sessions... But changing the data of the chart so that it shows only statistics for the current day/week is maybe useful to think about. It wouldn't consume much calculation and maybe would be more self explanatory. @binarious ?

**Comment by jiixing** [comment]
when I go to this tab, I am starting my meditation, so I prefer to have less information.

it is nice to see who is currently meditating or have finished.

it wouldn't look empty as I would think  retrieving the record for the past 24 hour should have some entries of those who finished

**Comment by binarious** [comment]
I also prefer to keep the chart. The idea to change it to the stats of the current day is a good idea. What would you prefer, @yuttadhammo?

**Comment by yuttadhammo** [comment]
I don't mind either way.
