### ISSUE TITLE
Add information on the ask tab

### ISSUE THREAD

**Issue by jiixing** [Sirimangalo/meditation-plus-angular#491]
It is not clear that questions are sorted by the upvotes, and what thumbs up do

suggestion:
add two buttons: sort by submission time, sort by votes
tooltips for the buttons: Questions are sorted by number of upvotes

Style thumb up button with border
tooltip to say:  Click this button to vote for this question

**Comment by olastor** [comment]
I'm closing this in favor of #530 
Let's move all the discussion about the questions tab there.
