### ISSUE TITLE
Stopping a meditation, then starting a new one, breaks the proper timing of the sound alerts. 

### ISSUE THREAD

**Issue by hookdump** [Sirimangalo/meditation-plus-angular#499]
I started a 19 minute walking + 15 minute sitting meditation.
Then I immediately stopped it.
And afterwards I started a 15 minute walking + 15 minute sitting meditation.

**Expected behavior:**

1. Start of walking meditation.
2. After 15 minutes, the alarm goes off.
3. Start sitting meditation.
4. After 15 minutes, the alarm goes off.

**Actual behavior:**

1. Start of walking meditation.
2. After 15 minutes, the alarm went off.
3. Start sitting meditation.
4. After 4 minutes, the alarm went off.
5. After 11 more minutes, (when the alarm should have sounded), no sound was played. Navigation went back to the list of meditators.
6. A few minutes after, another alarm went off.

Tomorrow I'll try to reproduce this on my local environment, and I'll probably develop a fix myself. Just publishing this note to avoid forgetting.

**Comment by olastor** [comment]
Thanks for submitting. Did you had the "stable Bell" option activated in your profile Page?

**Comment by hookdump** [comment]
"Stable Bell" option was not activated.
