### ISSUE TITLE
delete scheduled appointment after several no show

### ISSUE THREAD

**Issue by jiixing** [Sirimangalo/meditation-plus-angular#501]
I noticed an inactive user is still taking up an appointment slot.

The user name is 'Kev' I remember him from a few months ago. I saw his profile doesn't have a username yet, so I assume he hasn't logged in for a while.

**Comment by binarious** [comment]
Maybe he's still using this slot, but not using the app anymore. @yuttadhammo?

**Comment by yuttadhammo** [comment]
I think I'm going to have to go through the schedule and delete some
appointments... I think many are no longer valid.

**Comment by binarious** [comment]
That's the way we should deal with inactive appointments, I think. Closing this for now.
