### ISSUE TITLE
Extra badges for consecutive days meditating

### ISSUE THREAD

**Issue by FernandoDelta** [Sirimangalo/meditation-plus-angular#513]
In profile sometimes the app put extra badges. For example for 336 days meditating there should be two blue (160+160) and one black (10) badge but it shows two blue, one orange and one black badge (total of 370).
It is a minor thing that doesn't affect the functionality but I just wanted to let you know.
Thanks for maintaining this nice app.

**Comment by binarious** [comment]
Past consecutive days get badges, too. I think that is the case here with
your profile.

FernandoDelta <notifications@github.com> schrieb am So., 16. Juli 2017,
01:19:

**Comment by FernandoDelta** [comment]
Ok, thank you binarious. I didn't know that consecutive past days count too.
