### ISSUE TITLE
refactor hardcoded timezone 'America/Toronto'  for admin appointment scheduling

### ISSUE THREAD

**Issue by jiixing** [Sirimangalo/meditation-plus-angular#515]
If admin is travelling to  another timezone (e.g: europe or china) then the appointment scheduling will be wrong as it could be different day in different country.

_suggestion_: use admin timezone offset when checking for upcoming appointment.

I am currently writing more tests in appointment.component.spec to cover nextAppointments usage

**Comment by olastor** [comment]
good idea! I think we could build this ontop of the settings refactor. (https://github.com/Sirimangalo/meditation-plus-server/tree/refactor/appointment-increment)
