### ISSUE TITLE
Desktop notifications display after submitting offline meditation

### ISSUE THREAD

**Issue by johnjago** [Sirimangalo/meditation-plus-angular#523]
For example, on the profile page, I enter 10 minutes for walking, 10 minutes for sitting, and a time that is 20 minutes in the past. After 10 minutes, I will receive a desktop notification that walking meditation is complete. Same for sitting meditation. These notifications probably should not appear.

OS: Ubuntu 16.04
Browser: Firefox 54

**Comment by olastor** [comment]
@johnjago Thanks for spotting that error. It'll be fixed in the next release.
