### ISSUE TITLE
Meditation statistics for the month of August are displaying incorrect information

### ISSUE THREAD

**Issue by anafigueroa** [Sirimangalo/meditation-plus-angular#524]
Greetings
It seems that the meditation statistics chart for the "Last 10 months" (in the "Profile" section) is displaying wrong information for the month of August, showing more hours than it should. The other two charts seem to work fine. Other meditators have reported to experience the same issue.

**Comment by olastor** [comment]
@anafigueroa Thanks opening an issue.
