### ISSUE TITLE
Improve Questions Tab

### ISSUE THREAD

**Issue by olastor** [Sirimangalo/meditation-plus-angular#530]
The feature for starting answering a question doesn't seem to be used.

Idea:
- Remove answering feature
- Map every answered question with the broadcast url without time (User who really want to find the answer can search trough the video for the answer)
- add a search bar to the answered tab to filter answered questions

**Comment by jiixing** [comment]
My ideal solution would be for the answered questions to be public and have youtube timestamp link.

New feature:
- From the app, volunteer can see the list of answered question with answered date, and can edit the youtube link associated with it
- Record which volunteer who last edit the youtube link for the question.
- Publish the answered question with the youtube link on a publicly accessible page (this can also serve as FAQ)

Database : 
- add a new value for user.role 'ROLE_VOLUNTEER' 
- add a new field: user.capabilities = ['edit-question', ...]  in the future other volunteer can help edit other areas 
- add new fields question.editor  question.youtube

**Comment by olastor** [comment]
@jiixing That's sounds quite complex 😬 . Maybe we should first go with a simple solution and then think about whether such a feature is needed later (when we have a stable build with all the current PRs and changes applied).

**Comment by binarious** [comment]
> User who really want to find the answer can search trough the video for the answer

@olastor It's pretty hard to find these three minutes in a one hour video. Maybe we should ask for the reason why it's not used.

**Comment by jiixing** [comment]
Another solution that now Bhante has allocated a session to answer all questions is to have a  url that goes to the Answered tab, with parameter to filter the answers to a specific date.

currently https://meditation.sirimangalo.org/home;tab=ask  

to implement https://meditation.sirimangalo.org/home;tab=ask;pane=answered;date=2017-09-14

this way I can add this url in the youtube comments

**Comment by jiixing** [comment]
This feature will give more information for the weekly q/a video on YouTube . A way to see questions answered on a certain date , allow to see ahead of the questions answered on video. 

On older video Robin used to type in the questions manually in the YouTube comment

**Comment by olastor** [comment]
@jiixing I added some of the ideas to the Todo card in the question project. They are sorted by difficulty. If you want to implement one, feel free to pick one, but not from the ideas card, there are things that are not decided yet or are a 'nice to have' feature.

**Comment by binarious** [comment]
Closing this for now as the tab has been improved in the latest dev version. If we need anything else feel free to open a new issue at https://gitlab.com/sirimangalo/meditation-plus/issues
