### ISSUE TITLE
"Show email publicly" checkbox flashing issue

### ISSUE THREAD

**Issue by bkeevil** [Sirimangalo/meditation-plus-angular#54]
On the profile page I've run across a situation where clicking the "Show email publicly" checkbox has caused the checkbox to check and uncheck rapidly in a seemingly endless loop.  But it was not repeatable.  Might have something to do with my wonky 3rd world Internet connection.

**Comment by binarious** [comment]
Strange. Still in Firefox? I was not able to reproduce this bug.

**Comment by binarious** [comment]
Should be fixed with https://github.com/Sirimangalo/meditation-plus-angular/commit/f5e4762cf9f6b7a83b7f2497e1193fa83d6dcc4a.
