### ISSUE TITLE
Add a report system

### ISSUE THREAD

**Issue by olastor** [Sirimangalo/meditation-plus-angular#540]
- for reporting messages, questions.
- ~filter questions for bad words on server~

**Comment by binarious** [comment]
Reporting is ok. Obscenity filters [are problematic](https://blog.codinghorror.com/obscenity-filters-bad-idea-or-incredibly-intercoursing-bad-idea/).

**Comment by binarious** [comment]
Moved to https://gitlab.com/sirimangalo/meditation-plus/issues/14
