### ISSUE TITLE
use github projects feature to document roadplan

### ISSUE THREAD

**Issue by jiixing** [Sirimangalo/meditation-plus-angular#543]
I discovered github Projects (trello board) feature and think it would be good to use to document roadplan,  planned features

Example projects is here https://github.com/twbs/bootstrap/projects/8  https://github.com/twbs/bootstrap/projects/2

**Comment by olastor** [comment]
@jiixing Good idea. I personally don't know the feature very well. @binarious ?

**Comment by binarious** [comment]
Basically a nice feature, but we don't really need this. We have already used the milestones before and stopped using it, because there isn't much to plan and organize. But if you would like to give it a try and think we can benefit from that, then go for it.
