### ISSUE TITLE
Handle overflow text in a chat message

### ISSUE THREAD

**Issue by olastor** [Sirimangalo/meditation-plus-angular#57]
We should either set a limit for chat messages or adjust the styles so that long messages won't cause the style to collaps.

![Screenshot](https://cloud.githubusercontent.com/assets/7479641/17456255/e5265926-5bd1-11e6-8da9-25a487da8920.png)

**Comment by olastor** [comment]
Possible workaround: Put the message in a separate paragraph below the username.

**Comment by binarious** [comment]
:+1: I'm on it.
