### ISSUE TITLE
Remove `sw.js` from config

### ISSUE THREAD

**Issue by olastor** [Sirimangalo/meditation-plus-angular#576]
Just a quick note. I think this file does not exist anymore.

https://github.com/Sirimangalo/meditation-plus-angular/blob/83e51bd7985c818630c635f7e82e861e527c9a5d/.angular-cli.json#L13

**Comment by binarious** [comment]
IIRC it gets created by https://github.com/Sirimangalo/meditation-plus-angular/blob/83e51bd7985c818630c635f7e82e861e527c9a5d/package.json#L15
