### ISSUE TITLE
Disable Autocomplete on mobile devices

### ISSUE THREAD

**Issue by olastor** [Sirimangalo/meditation-plus-angular#578]
... to increase performance

**Comment by binarious** [comment]
I don't think that we gain a lot of performance with this. I'd rather optimize the UX to make it usable on mobile. What do you think?

**Comment by olastor** [comment]
I agree, but I meant that typing and deleting in the message input is quite laggy and slow (at least for me). Maybe removing the change event on smartphones could resolve this. It wouldn't make a difference anyway since they is no tab key.

**Comment by binarious** [comment]
Moved to https://gitlab.com/sirimangalo/meditation-plus/issues/6
