### ISSUE TITLE
Autocompletion of usernames in chat + mentioning feature

### ISSUE THREAD

**Issue by olastor** [Sirimangalo/meditation-plus-angular#58]
Implement `@user` syntax with autocomplete and mentioning (if oneself is mentioned in chat).

**Comment by binarious** [comment]
Blocked by https://github.com/angular/material2/issues/117

**Comment by olastor** [comment]
Seems they have removed the blocked  Tag.

**Comment by binarious** [comment]
Yep, should be ready soon.

**Comment by binarious** [comment]
They released the doc: https://github.com/angular/material2/blob/3d236a64986bad7ff346bee613b3b2737f6f5567/src/lib/autocomplete/OVERVIEW.md
Now we just have to think about how to identify people since we removed the usernames.

**Comment by olastor** [comment]
https://github.com/angular/material2/releases New release with this feature came out.

**Comment by olastor** [comment]
`md-autocomplete` doesn't work for textareas. But we should use a textare for the chat box because of the autogrow feature...

**Comment by binarious** [comment]
There is angular2-mention. Can you check that out?

Sebastian K. <notifications@github.com> schrieb am Do., 23. Feb. 2017,
09:28:

**Comment by olastor** [comment]
@binarious It requires bootstrap css, though. This might mess up our styles.

**Comment by binarious** [comment]
You could fork it and make it use material design.

Sebastian K. <notifications@github.com> schrieb am Do., 23. Feb. 2017,
09:39:

**Comment by olastor** [comment]
@binarious I noticed that the chat input is already a bit laggy when typing fast. Adding the autocomplete and adding new events would make it even heavier. How about recognizing/matching "@name" on the server site and focus on push notifictions?

**Comment by binarious** [comment]
@olastor The name isn't unique. We can't match that on the server-side. The user has to choose which user to mention. We should optimize the chat's performance.

**Comment by olastor** [comment]
@binarious But if the names aren't unique how should you as a user be able to choose the right name between to duplicates in the first place? Maybe we should think about making names unique, if that's possible

**Comment by binarious** [comment]
They could choose from a drop down list via avatar, but you're right. It is not ideal. Maybe we should reintroduce usernames. It would make things easier.

**Comment by olastor** [comment]
I maybe have an idea. Will try something
