### ISSUE TITLE
Blacklist spam email providers for signup

### ISSUE THREAD

**Issue by olastor** [Sirimangalo/meditation-plus-angular#590]
Some potentially malicious user have tried to signup with temporary emails (like https://10minutemail.com/). Blacklisting such websites seems like a good idea to make it more complicated to create a "spam account".

We could use this list for example: https://raw.githubusercontent.com/ivolo/disposable-email-domains/master/index.json

Maybe this would need to be added as a seperate config file to not expose the repository to searches for domains like this (?!).

**Comment by binarious** [comment]
Moved to https://gitlab.com/sirimangalo/meditation-plus/issues/1
