### ISSUE TITLE
Hightlight mentioning

### ISSUE THREAD

**Issue by binarious** [Sirimangalo/meditation-plus-angular#63]
A user should receive a notification when he is mentioned.

**Comment by yuttadhammo** [comment]
The android app added a (1) to the Chat tab to let you know there was a message waiting for you in that tab... maybe that would work?

**Comment by binarious** [comment]
Yes, that sounds better.

**Comment by binarious** [comment]
The highlighting has to be done via id since we removed the usernames. I would use a syntax like `[@myid]` which will be generated client-side via autocompletion. On the server-side this part will removed and the mention will be added as metadata to the message. Because of that, this issue is blocked until material2 adds autocompletion.

**Comment by olastor** [comment]
Also featuring Push Notifications would be an idea for later.

**Comment by binarious** [comment]
We could use https://github.com/dmacfarlane/angular2-mentions for this. But it's still very buggy and doesn't have a lot of attention, yet. I have created a fork of it. Maybe I'll find some time to make it useable for us.

**Comment by olastor** [comment]
https://github.com/angular/material2/tree/master/src/lib/autocomplete Seems to be published very soon.

**Comment by olastor** [comment]
This feature seems to be already acknowledged in #58. Please reopen, if I got it wrong.
