### ISSUE TITLE
Daily livestream

### ISSUE THREAD

**Issue by binarious** [Sirimangalo/meditation-plus-angular#67]
@yuttadhammo How does it work in the current version?

**Update**: Check for http://sirimangalo.org:8000/live

**Comment by yuttadhammo** [comment]
It checks for the existence of the feed url and shows a flash player if found

**Comment by binarious** [comment]
Is it a YouTube stream? Can't we embed the YouTube player then? Flash is dead 😄.

**Comment by yuttadhammo** [comment]
It's mp3 so maybe a html5 video element? I don't know how to embed YouTube because it's a different url every night

**Comment by binarious** [comment]
Mp3 would be audio only. Do you mean mp4 or an audio element? How do you check for the existence of the feed when the url is different every night?

**Comment by yuttadhammo** [comment]
We use icecast to broadcast and record the sessions in mp3, separate from
YouTube. It's not really necessary i suppose, but i sometimes give audio
only broadcast when traveling.

**Comment by doksu** [comment]
@binarious the url is always the same. It's been moved to the new server: https://broadcast.sirimangalo.org/live

**Comment by binarious** [comment]
The livestream time is fixed to 0100h UTC.
