### ISSUE TITLE
Clicking a new appointment in schedule changes the users appointment timeslot or cancels appointment.

### ISSUE THREAD

**Issue by bkeevil** [Sirimangalo/meditation-plus-angular#70]
The old behavior, if I recall correctly, was that a user  could change their timeslot by clicking on a new timeslot or cancel an appointment by clicking on the scheduled appointment.  I liked it, it was simple and intuitive.

**Comment by binarious** [comment]
The old way was the same as it is now, but your idea is more intuitive nevertheless.
