### ISSUE TITLE
Emoji tags should be case insensitive

### ISSUE THREAD

**Issue by bkeevil** [Sirimangalo/meditation-plus-angular#71]
The emoji tags are currently case sensitive.  If I type :Question: instead of :question: then the emoji won't display at all.  I think a captialized Q might be a common user error and could cause problems.  Same with the other emojis.

**Comment by binarious** [comment]
This is the default behaviour regarding emojis. GitHub ignores the :Question: tag, too. This won't be a problem in the future when we have autocompletion for emojis. But the `Q:` should be considered, I guess. What are your thoughts @olastor? Can you add it to your branch?

**Comment by olastor** [comment]
I'll add it :+1:
