### ISSUE TITLE
Button to join google hangouts doesn't show up

### ISSUE THREAD

**Issue by bkeevil** [Sirimangalo/meditation-plus-angular#76]
I booked an appointment and waited for the button to show up.  The div block asking me to click the button showed up but no button.  See screenshot

![screenshot](https://cloud.githubusercontent.com/assets/2401838/17459426/0b645344-5c05-11e6-9ad7-de3414c7173b.png)

**Comment by binarious** [comment]
That's the discussion we were having in Slack. We can't access the hangout feature via Google's API. Error: `Cannot read property 'render' of undefined`. Stopped working on the old page, too.

**Comment by bkeevil** [comment]
Oh ok.  I thought that was only with the old site.

**Comment by binarious** [comment]
Should be working now (see issue @ code.google.com).
