### ISSUE TITLE
Meditation Statistics/History Report

### ISSUE THREAD

**Issue by bkeevil** [Sirimangalo/meditation-plus-angular#81]
Feature Request.  My main gripe about the old site was that there was no way to see how much meditation you had done in the past day, week or month.  Maybe some other useful statistics can be garnered.  We could probably dump the last 7 days of the users meditation log data as well to address "was that meditation logged correctly by the system" type questions.

**Comment by binarious** [comment]
Absolutely agree on that. Closing this issue since that's what https://github.com/Sirimangalo/meditation-plus-angular/issues/50 is meant to represent. We need to create separate issues for the ideas later.
