### ISSUE TITLE
Support layout without tab

### ISSUE THREAD

**Issue by medhinidotnet** [Sirimangalo/meditation-plus-angular#83]
Another idea for Bhante: I just watched the last two vid's. In one he states that he likes the old layout where stuff is on one page. Maybe he could get this in this new environment as well? Layout linked to his profile where everything he wants is on one page. Like you can create your own environment in Jira. Don't know if you know Jira though. :)

**Comment by binarious** [comment]
@yuttadhammo interested? :)

**Comment by yuttadhammo** [comment]
Hey if we could change the layout individually that would be great... If it's not too much trouble, maybe just two choices, single page or tabbed... I don't mind the tabbed interface so much, actually

**Comment by binarious** [comment]
- [ ] Add option to the settings to choose layout
- [ ] Single page layout would add "Commit" to the sidenav and display "Meditation" and "Chat" on "Home". One below the other.
- [ ] Tab page layout (default) would be the same as it is now
