### ISSUE TITLE
Commitments on commit page should be mutual exclusive.

### ISSUE THREAD

**Issue by medhinidotnet** [Sirimangalo/meditation-plus-angular#84]
About the Commitments on the Commit page. I think they should be mutual exclusive. One can't commit to meditating 20 min a day and make another commitment for 60 min a day. What does one do? 60 min or 20 min? If I do 60 min I automatically also do 20. But if I do 20 min I would have to do another 60 for that commitment. Which is actually 80 min on that day. See where I'm getting? It's not logical the way it is now

**Comment by yuttadhammo** [comment]
I don't think we need to be this strict... it would be complicated, as some commitments are potentially compatible with others
