### ISSUE TITLE
Create separate page/tab for questions for Bhante

### ISSUE THREAD

**Issue by medhinidotnet** [Sirimangalo/meditation-plus-angular#85]
Idea maybe: Is it an idea to have a separate page/tab for the questions for Bhante? So that it is easier to find them and the chat is/becomes really more of a chat to connect to each other? But maybe this has to be discussed w/ Bhante first.

**Comment by olastor** [comment]
@yuttadhammo Would you like a personal area/site with all the questions? Currently all questions marked with :question:, 'Q/q:' will have a green highlight.

**Comment by yuttadhammo** [comment]
Yeah, if you could manage it, that would be great... If there were a way to
click a question as answered and highlight it a different color or
something, that might be nice too

**Comment by yuttadhammo** [comment]
Also, is there a way to make someone else admin?

**Comment by olastor** [comment]
@yuttadhammo You'd probably need to manually entry a new user into the DB with the property `role: 'ROLE_ADMIN'`. @binarious Is that right?

**Comment by binarious** [comment]
We have https://github.com/Sirimangalo/meditation-plus-angular/issues/13 on our list. But for now I'm doing it via command line directly on the db.

**Comment by binarious** [comment]
I like simplicity :). What about a checkbox "questions only" in the chat tab for admins? Plus the functionality to mark one as answered (admins only, too, of course).

**Comment by yuttadhammo** [comment]
yes, that sounds better... just a filter... though we could maybe make the filter open to everyone?

**Comment by olastor** [comment]
ToDo:
- [x] Added button to toggle 'Show only questions in chat'
- [ ] Add for admin: mark question as answered

**Comment by binarious** [comment]
Done via #99 and #101
