### ISSUE TITLE
Make usernames on all tabs clickable

### ISSUE THREAD

**Issue by medhinidotnet** [Sirimangalo/meditation-plus-angular#86]
Preferable the profile page then opens in a new browser window

**Comment by binarious** [comment]
Good idea. It shouldn't open in a new browser window though since it's a single page application and should behave like a native app.

**Comment by medhinidotnet** [comment]
Guess I meant browser tab. Thanx :)

**Comment by binarious** [comment]
@bkeevil This would be a good starting point I guess.
