### ISSUE TITLE
Make url's on profile pages clickable

### ISSUE THREAD

**Issue by medhinidotnet** [Sirimangalo/meditation-plus-angular#87]
Preferable page opens in new browser window

**Comment by binarious** [comment]
Already done in https://github.com/Sirimangalo/meditation-plus-angular/commit/44eda40a21f3c983fd6f9e7d04f8b32ed4c3c21c

**Comment by medhinidotnet** [comment]
Hi there. It's not working though. How come?

**Comment by binarious** [comment]
It will be shipped with version 0.8.0 which isn't released, yet.

**Comment by medhinidotnet** [comment]
Ah, ok. thanx
