### ISSUE TITLE
Make usernames in links visible

### ISSUE THREAD

**Issue by medhinidotnet** [Sirimangalo/meditation-plus-angular#88]
When I on the Commit-page move with the mouse over a picture/avatar of a person the link at the bottom of my browser shows not the name but a very long number/key. Is it possible to show the actual username in the link?

**Comment by olastor** [comment]
@medhinidotnet The server & database needs a unique key to identify the user. The 'primary id' is an email address (means you cannot change your email once you've signed up), the name however is editable, which is meant to improve the general appearance (you can change it and have duplicates). 

Therefore it's not possible to use the name as a link.

**Comment by medhinidotnet** [comment]
What about a little pop-up or something that let's me know I have the correct person?

**Comment by binarious** [comment]
Already answered this in the chat:
> Medhini, there are no unique usernames anymore. Just email, id (very long number) and a generic name field (can't use this for a link). But a tooltip with the name would be useful there I guess.

You can change your email though (in future releases) since the real unique identifier gets generated on signup.

Pop-up/tooltip already done in https://github.com/Sirimangalo/meditation-plus-angular/commit/e9a6180c5c74e48b4759636feb5e9cfc14429200.

**Comment by medhinidotnet** [comment]
Thanx:)
