### ISSUE TITLE
Wrap lines input to one screen

### ISSUE THREAD

**Issue by ghost** [Sirimangalo/meditation-plus-angular#89]
When I post a long question (and I do) or put in a long description on my profile page I would have to scrol way back to check my input. If it's wrapped to one screen I can actually read what I wrote

**Comment by binarious** [comment]
Right. The input field should probably grow while typing.

**Comment by binarious** [comment]
Blocked by https://github.com/angular/material2/issues/546

**Comment by binarious** [comment]
I think we should just use http://www.primefaces.org/primeng/#/inputtextarea.

**Comment by binarious** [comment]
The material textarea component is released with autosize. I'll implement this soon.
