### ISSUE TITLE
Testimonials Page

### ISSUE THREAD

**Issue by binarious** [Sirimangalo/meditation-plus-angular#9]
The idea is to add a testimonials page where meditators could share the benefits of the practice. 
It would consist of a user submission form and admin review queue.

**Comment by olastor** [comment]
- [x] Basic mongoose scheme for server
- [x] Working with modified /message copy
- [ ] Display datetime, not 'ago'
- [ ] Customize style
- [ ] Add description
- [ ] Show only reviewed testimonials

**Comment by binarious** [comment]
Done. The rest is #13. Thank you, @olastor.
