### ISSUE TITLE
Make chat messages editable and deletable

### ISSUE THREAD

**Issue by medhinidotnet** [Sirimangalo/meditation-plus-angular#90]
Now I can't edit or delete a post once made. Would be nice though if one could to clarify or edit in case of lot's of errors for instance.

**Comment by olastor** [comment]
@medhinidotnet By 'post' do you mean a chat message, meditation or something else??

**Comment by medhinidotnet** [comment]
Chat message. Sorry. :)

**Comment by binarious** [comment]
We already have the basic functionality for that in https://github.com/Sirimangalo/meditation-plus-angular/blob/0f773709cf336c5f48b3b4d69acd960d8559acce/src/app/message/message.component.ts#L124. Just need an update/delete rest endpoint and buttons.

**Comment by yuttadhammo** [comment]
I don't think this is necessary... actually might be problematic, since it means someone could say something problematic and then erase it so we wouldn't be able to investigate.

**Comment by binarious** [comment]
We could follow the Gitter approach: editable just for some minutes after sending. Deletable forever, but still visible (text shows "This message has been deleted."). Could still be visible to admins, though.

**Comment by binarious** [comment]
We need a menu for that which was added in material alpha 7 and its integration is blocked by https://github.com/Sirimangalo/meditation-plus-angular/issues/166

**Comment by binarious** [comment]
Not blocked anymore since we updated to alpha 7.

**Comment by binarious** [comment]
@yuttadhammo Are you fine with the Gitter approach or shall we stop looking into this feature?

**Comment by yuttadhammo** [comment]
I'm okay with either.
